#!/usr/bin/env python3

from os import system as sys
import subprocess

class Main:	
    def __init__(self, packages, parupkg):
        self.packages = packages
        self.parupkg = parupkg

    def run_command(self, command):
        """Helper method to run commands sequentially"""
        print(f"\n[>>] Executing: {command}")
        result = subprocess.run(command, shell=True)
        if result.returncode != 0:
            print(f"[!!] Error executing: {command}")
        return result

    def install(packages):
	    self.run_command(f"sudo pacman -Syu --needed {' '.join(packages)}")

    def pinstall(packages):
	    self.run_command(f"paru -Syu --needed {' '.join(packages)}")

    def base(self, packages):
        self.install(packages)
        self.run_command("sudo cp ./bin/update-grub /usr/local/bin")
        self.run_command("sudo chmod +x /usr/local/bin/update-grub")

    def nm_fixes(self):
        self.run_command("sudo systemctl enable --now systemd-resolved")
        self.run_command("sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf")
        self.run_command("sudo cp ./config/nm/dns.conf /etc/NetworkManager/conf.d/")
        self.run_command("sudo systemctl restart NetworkManager")

    def cp_config(self):
        self.run_command("mkdir -p ~/.config-backup")
        config_dirs = ["mako", "hypr", "rofi", "waybar", "foot"]
        for dir in config_dirs:
            self.run_command(f"rm -rf ~/.config/{dir}")
        for dir in config_dirs:
            self.run_command("cp -r config/{dir}} ~/.config")
        self.run_command("cp -r Pictures ~/")

    def base_paru(self, packages):
        if packages:
            self.pinstall(packages)

    def fish(self):
        self.run_command("sudo chsh -s /bin/fish")
        self.run_command("chsh -s /bin/fish")

    def paru(self):
        self.run_command("git clone https://aur.archlinux.org/paru.git")
        self.run_command("cd paru && makepkg -si --noconfirm")
        self.run_command("cd ../ && rm -rf ./paru")

    def fastest_mirrors(self):
        self.run_command("sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup")
        print("[**] Finding fastest mirrors...")
        self.run_command("rate-mirrors arch | sudo tee /etc/pacman.d/mirrorlist")

    def setup_udisks(self):
        self.run_command("sudo cp config/system/mount_options.conf /etc/udisks2")
        self.run_command("sudo systemctl restart udisks2")

    def setup_login_manager(self):
        self.run_command("sudo systemctl enable --now ly@tty1")

    def main(self):
        print("\n" + "="*50)
        print("INSTALLATION STARTED")
        print("="*50 + "\n")
        
        # 1. Base packages installation
        print("\n[1/10] Installing base packages...")
        self.base(self.packages)
        
        # 2. Fish shell installation
        print("\n[2/10] Installing and configuring fish...")
        self.fish()
        
        # 3. Paru installation
        print("\n[3/10] Installing paru (AUR helper)...")
        self.paru()
        
        # 4. Mirror optimization
        print("\n[4/10] Optimizing mirrors...")
        self.fastest_mirrors()
        
        # 5. AUR packages installation
        print("\n[5/10] Installing AUR packages...")
        self.base_paru(self.parupkg)
        
        # 6. Config files copying
        print("\n[6/10] Copying configuration files...")
        self.cp_config()
        
        # 7. NetworkManager configuration
        print("\n[7/10] Configuring NetworkManager...")
        self.nm_fixes()
        
        # 8. Udisks2 configuration
        print("\n[8/10] Configuring udisks2...")
        self.setup_udisks()
        
        # 9. Login manager setup
        print("\n[9/10] Enabling login manager (ly)...")
        self.setup_login_manager()
        
        print("\n" + "="*50)
        print("INSTALLATION COMPLETE!")
        print("="*50 + "\n")

if __name__ == "__main__":
    packages = [
        "linux-zen",
        "linux-zen-headers",
        "base-devel",
        "git",
        "python",
        "nano",
        "fastfetch",
        "os-prober",
        "nvidia-open-dkms",
        "nvidia-utils",
        "lib32-nvidia-utils",
        "egl-wayland",
        "pipewire",
        "pipewire-pulse",
        "wireplumber",
        "pavucontrol",
        "hyprland",
        "wayland",
        "wayland-protocols",
        "xdg-desktop-portal-hyprland",
        "xdg-desktop-portal-gtk",
        "noto-fonts",
        "noto-fonts-emoji",
        "noto-fonts-cjk",
        "ttf-dejavu",
        "ttf-liberation",
        "ttf-fira-code",
        "foot",
        "hyprpaper",
        "polkit-gnome",
        "mako",
        "nautilus",
        "rofi",
        "firefox",
        "ly",
        "network-manager-applet",
        "ntfs-3g",
        "waybar",
        "qt5ct",
        "qt6ct",
        "ttf-jetbrains-mono-nerd",
        "copyq",
        "hypridle",
        "hyprlock",
        "python-gobject",
        "hyprshot",
        "gnome-themes-extra",
        "woff2-font-awesome",
        "otf-font-awesome",
        "gnome-system-monitor",
        "networkmanager",
        "grub",
        "github-cli",
        "telegram-desktop",
        "steam",
        "discord",
        "prismlauncher",
        "code",
        "fish"
    ]

    parupkg = [
        "rate_mirror",
        "amneziavpn",
        "xone-dkms",
        "jdk21-temurin"
    ]

    main = Main(packages, parupkg)
    main.main()
