exec-once = nm-applet
exec-once = hypridle
exec-once = hyprpaper 
exec-once = waybar 
exec-once = mako
exec-once = copyq --start-server
exec-once = $polkit
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = flameshot
