exec-once = nm-applet & hypridle
exec-once = hyprpaper & waybar & mako & copyq --start-server
exec-once = $polkit
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = flameshot
exec-once = $dock
