windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
	name = Firefox PiP
	match:class = ^([Ff]irefox)
	match:title = Picture(-| )in(-| )[Pp]icture
	float = yes
	pin = yes
	border_size = 0
	size = 640 360
   	keep_aspect_ratio = yes
	opacity = 2
}

windowrule {
	name = CopyQ
	match:class = com.github.hluk.copyq

	float = yes
	pin = yes
#	stay_focused = yes
}

windowrule {
	name = polkit-gnome
	match:class = polkit-gnome-authentication-agent-1
	stay_focused = yes
}


windowrule {
	name = idea-win-smth
	match:class = .*jetbrains.*
	match:title = win.*
	stay_focused = true
}

windowrule {
	name=port-proton
	match:class = PortProton
	float = yes
}

windowrule {
	name=tf2-fix
	match:class = tf_linux64
	fullscreen = true
}

windowrule {
	name=flameshot-fix
	match:class = flameshot
	float = on
	monitor = 0
	move = 0 0
	size = 100% 100%
	no_anim = on
	decorate = off
	no_dim = on
	no_blur = on
	stay_focused = on	
	rounding = 0
	border_size = 0
	dim_around = off
	focus_on_activate = on
	opaque = on
	fullscreen = on
}
