windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
	name = Firefox PiP
	match:class = ^([Ff]irefox)
	match:title = Picture(-| )in(-| )[Pp]icture
	float = yes
	pin = yes
	border_size = 0
	size = 640 360
   	keep_aspect_ratio = yes
	opacity = 2
}

windowrule {
	name = CopyQ
	match:class = com.github.hluk.copyq
	float = yes
	pin = yes
#	stay_focused = yes
}

windowrule {
	name = polkit-gnome
	match:class = polkit-gnome-authentication-agent-1
	stay_focused = yes
}


windowrule {
	name = idea-win-smth
	match:class = .*jetbrains.*
	match:title = win.*
	stay_focused = true
}
