[General]
activeIndicatorColor=#ff8c00
activeIndicatorColor2D=#00ffff
backgroundColor=#6b638abd
backgroundColor2D=#ff0b1220
borderColor=#99addd
bouncingLauncherIcon=true
firstRunWindowCountIndicator=false
floatingMargin=10
inactiveIndicatorColor=#008b8b
inactiveIndicatorColor2D=#e6e8ee
maximumIconSize=90
minimumIconSize=48
panelStyle=2
showTooltip=true
spacingFactor=0.6
tooltipFontSize=16
zoomingAnimationSpeed=16

[Application%20Menu]
backgroundAlpha=0.5
fontSize=16
iconSize=32
label=Applications

[Clock]
fontScaleFactor=1
use24HourClock=true

[TaskManager]
currentDesktopTasksOnly=false
groupTasksByApplication=true
